controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: 'App\Controller\DefaultController::index'
product_list:
    path: /products
    controller: App\Controller\ProductController::list

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show
